Added bus time
autowarefoundation/ros2_socketcan pull request #12
Opened 2021-11-14 22:05 UTC by asaba96

added the ability to get the bus time for the can packet, versus using ros time when received; packs bus time as part of the can id struct

This packs the bus time in the `CanId` object vs returns it as a tuple. I'll let the maintainers decide which they prefer :) 

Tested w. a can replay on my machine, using canreplay on a virtual can bus

@JWhitleyWork

2021-11-16 16:15 UTC, JWhitleyWork requested changes
Just a minor change.

2021-11-16 16:15 UTC, JWhitleyWork commented on include/ros2_socketcan/socket_can_common.hpp
> +    return uint64_t(tv.tv_sec)*1e6 + tv.tv_usec;
Please use a modern cast (e.g. `static_cast<uint64_t>()`).

2021-11-16 16:15 UTC, JWhitleyWork commented
@mitsudome-r or @bonolo Can one of you please approve the workflow for this PR?

2021-11-17 21:48 UTC, asaba96 commented on include/ros2_socketcan/socket_can_common.hpp
> +    return uint64_t(tv.tv_sec)*1e6 + tv.tv_usec;
fixed

2021-11-17 21:50 UTC, JWhitleyWork approved these changes

2021-12-11 05:20 UTC, JWhitleyWork approved these changes
LGTM. Waiting for someone from AWF to merge.

2021-12-13 10:42 UTC, wep21 commented
@asaba96 Could you fix the linter errors?

2022-02-03 08:00 UTC, merged